import os
import psycopg
from psycopg.rows import dict_row


def get_connection():
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL must be set to connect to PostgreSQL")
    return psycopg.connect(database_url, row_factory=dict_row)


def initialize_database():
    with get_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
                stock INTEGER NOT NULL CHECK (stock >= 0),
                image TEXT NOT NULL
            )
            """
        )
        connection.execute(
            "ALTER TABLE products ALTER COLUMN price "
            "TYPE NUMERIC(10, 2) USING price::NUMERIC(10, 2)"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS idx_products_category_lower "
            "ON products (LOWER(category))"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS idx_products_name_category_lower "
            "ON products (LOWER(BTRIM(name)), LOWER(BTRIM(category)))"
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('user', 'admin'))
            )
            """
        )